### ISSUE TITLE
Discussion

### ISSUE THREAD

**Issue by llvee** [elicit/Debate#1]
Interested in discussing about work opportunities at Elicit. Interested in helping out with product engineering as I have spent lots of time analysing research studies manually. I am not presently using other relevant social channels so chatting here for time savings.

**Comment by llvee** [comment]
@jungofthewon @goodgravy @stuhlmueller @reppertj @stuhlmueller  

I didn't notice any activity on this for a week now, tagging you all for visibility. I have a lot of great technology, research, business & communications experience that would be really helpful for the team. I have done a lot of independent non paid work which has helped me develop a useful skillset. 

I also identify as a humanitarian. I get a-long pretty easily with others in team environments. I am interested in helping out remotely, hybridly or in person depending on team needs. 

I am wanting to travel more while working on humanitarian works, continuing to learn & contributing to tech products. I am also up for other work types depending as I enjoy being a dynamic person.  

I am also up to share more about myself over Zoom or possibly another channel. I like making new friends also so up for team building exercises prior to interviewing if you all want to try something like that.

**Comment by reppertj** [comment]
Thanks for reaching out! Check out our opportunities at https://elicit.com/careers -- that's the best place to let us know your interest and apply.

**Comment by llvee** [comment]
@reppertj You're welcome. I submitted an application previously. I lost access to the email account used to apply, this has been my constant dilemma with applying to technology jobs while living temporarily domestic nomadically in a low resource situation due to circumstances partially out of my control. I will also apply through there again. 

Due to present circumstances for best results it would likely be better to arrange interviews via messaging vs the normal application process if possible? This should also save your team time. I have also found that many application processes are inefficient due to team interviews requiring resharing resume, application information via speech. 

I have many years of technology work experience. I have worked as a freelancer, consultant, founder, & employee in multiple company types. I can also share past work references, examples. I fully understand the problem domain due to spending lots of time analysing research papers, conducting quantitative, & qualitative research independently.

**Comment by llvee** [comment]
@reppertJ 

I am wondering if there may be support for new product or feature development focused on integrations with OpenAI, Gemini, Copilot, Huggingface & similar companies? 

Are plans to continue development internally in a non FOSS environment? 

Is there any specific open source of truth for current product features?
